clickhouse:
  addresses:
    - sql-clickhouse.clickhouse.com:9440
  tls: true
  database: default
  username: demo
  password: ""

alertmanager:
  scheme: http
  static_config:
    targets:
      - localhost:9093

rule_files:
  - alerts.yaml

evaluation_interval: 30